const state={page:"dashboard",accounts:[],programs:[],tasks:[],runs:[],selectedRun:null,runtime:{}};
const titles={dashboard:["概览","任务运行和浏览器资源概况"],accounts:["账户与浏览器","统一查看账户、浏览器身份与任务占用"],tasks:["任务管理","创建可重复运行的 Task 配置"],runs:["运行记录","查看 TaskRun 状态、日志、输出和错误"],programs:["任务程序","随代码部署的只读程序目录"],ai:["AI 服务","模型连接和提示词模板"],settings:["系统设置","Runner 资源与取消策略"]};
const $=id=>document.getElementById(id);
const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const json=value=>JSON.stringify(value??{},null,2);
const ident=item=>item.id||item.account_id||item.acc||"";
const statusBadge=s=>`<span class="status ${esc(s||"unknown")}">${esc(s||"-")}</span>`;
const when=value=>value?new Date(value).toLocaleString("zh-CN",{hour12:false}):"-";

async function api(path,options={}){const response=await fetch(`/api${path}`,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:json(body.detail||body));return body}
function flash(message,error=false){$("flash").innerHTML=`<div class="flash ${error?"error":""}">${esc(message)}</div>`;setTimeout(()=>$("flash").replaceChildren(),3200)}
function table(headers,rows,empty="暂无数据"){if(!rows.length)return `<div class="empty">${esc(empty)}</div>`;return `<table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table>`}
function taskState(account){return account.task_status||account.taskStatus||"idle"}
function browserState(account){return account.browser_status||account.browserStatus||account.runtime?.status||"stopped"}

async function showPage(page){state.page=page;document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===`page-${page}`));document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("pageTitle").textContent=titles[page][0];$("pageSubtitle").textContent=titles[page][1];try{await loaders[page]()}catch(error){flash(error.message,true)}}

async function loadDashboard(){const data=await api("/dashboard");const summary=data.summary||data;const cards=[["浏览器账户",summary.account_count??summary.browser_accounts??0],["运行中浏览器",summary.running_browsers??0],["正在运行 TaskRun",summary.running_runs??0],["等待运行 TaskRun",summary.queued_runs??0],["今日成功",summary.succeeded_today??0],["今日失败",summary.failed_today??0],["结果不确定",summary.uncertain_runs??0],["浏览器并发槽位",summary.execution_slots||`${summary.slots_used??0} / ${summary.slots_total??0}`]];$("summaryCards").innerHTML=cards.map(([label,value])=>`<div class="card"><small>${label}</small><strong>${esc(value)}</strong></div>`).join("");const runRows=(data.running||data.running_runs_detail||[]).map(run=>`<tr><td>${esc(run.task_name||run.task_id||"-")}</td><td>${esc(run.program_name)}</td><td>${esc(run.account_name||run.account_id)}</td><td>${statusBadge(run.status)}</td><td>${when(run.started_at)}</td><td><button class="link-button" data-run-view="${esc(run.id)}">查看</button> <button class="link-button" data-run-cancel="${esc(run.id)}">取消</button></td></tr>`);$("runningTable").innerHTML=table(["任务","程序","账户","状态","开始时间","操作"],runRows);const badRows=(data.failures||data.recent_failures||[]).map(run=>`<tr><td>${esc(run.task_name||run.id)}</td><td>${statusBadge(run.status)}</td><td>${esc(run.error?.code||run.error_code||"-")}</td><td>${when(run.finished_at||run.created_at)}</td></tr>`);$("failureTable").innerHTML=table(["运行","状态","错误","时间"],badRows,"暂无近期异常");const upcoming=(data.upcoming||[]).map(task=>`<tr><td>${esc(task.name)}</td><td>${when(task.schedule?.next_run_at||task.schedule?.run_at)}</td><td>${esc((task.account_ids||[]).length||task.account_count||1)}</td></tr>`);$("upcomingTable").innerHTML=table(["任务","下次执行","账户数"],upcoming,"暂无启用的计划")}

async function loadAccounts(){state.accounts=(await api("/accounts")).accounts||[];const rows=state.accounts.map(account=>{const id=ident(account);const fp=account.fingerprint||{};return `<tr><td><input type="checkbox" class="account-select" value="${esc(id)}"></td><td><strong>${esc(account.name||account.display_name||id)}</strong><div class="muted">${esc(account.username?`@${String(account.username).replace(/^@/,"")}`:"未绑定 X 用户名")}</div></td><td>${(account.tags||[]).map(tag=>`<span class="status">${esc(tag)}</span>`).join(" ")||"-"}</td><td><div class="state-stack"><span class="browser">${statusBadge(browserState(account))}</span><span class="task">${statusBadge(taskState(account))}</span></div></td><td>${esc(fp.region||account.proxy_region||"-")}<div class="muted">${esc(fp.timezone||account.timezone||"")} ${esc(fp.locale||account.locale||"")}</div></td><td>${esc(fp.browserVersion||account.browser_version||"-")}</td><td><div class="row-actions"><button class="link-button" data-browser="open" data-account="${esc(id)}">打开</button><button class="link-button" data-browser="close" data-account="${esc(id)}">关闭</button><button class="link-button" data-browser="restart" data-account="${esc(id)}">重启</button></div></td></tr>`});$("accountsTable").innerHTML=table(["选择","账户","标签","资源状态","网络身份","浏览器版本","操作"],rows,"尚无账户")}

async function loadPrograms(){state.programs=(await api("/task-programs")).programs||[];$("programCards").innerHTML=state.programs.length?state.programs.map(program=>`<div class="program-card"><h3>${esc(program.title||program.name)}</h3><div><code>${esc(program.name)}</code> · ${esc(program.version||"-")}</div><p>${esc(program.description||"")}</p><pre>${esc(json(program.params_schema||program.schema||{}))}</pre></div>`).join(""):`<div class="empty">尚未注册任务程序</div>`}

function taskRow(task){const ids=task.account_ids||[task.account_id].filter(Boolean);return `<tr><td><button class="link-button" data-task-edit="${esc(task.id)}">${esc(task.name)}</button><div class="muted">${esc(task.description||"")}</div></td><td><code>${esc(task.program_name)}</code><div class="muted">${esc(task.program_version||"")}</div></td><td>${esc(ids.length)} 个账户</td><td>${statusBadge(task.enabled?"enabled":"disabled")}</td><td>${esc(task.schedule?.summary||task.schedule?.cron||"手动")}</td><td><div class="row-actions"><button data-task-run="${esc(task.id)}">立即运行</button><button class="secondary" data-task-edit="${esc(task.id)}">编辑</button><button class="secondary" data-task-clone="${esc(task.id)}">复制</button><button class="link-button" data-task-toggle="${esc(task.id)}" data-enabled="${task.enabled?"false":"true"}">${task.enabled?"停用":"启用"}</button><button class="danger" data-task-delete="${esc(task.id)}" data-task-name="${esc(task.name)}">删除</button></div></td></tr>`}
async function loadTasks(){const [tasks,programs,accounts,runtime]=await Promise.all([api("/tasks"),api("/task-programs"),api("/accounts"),api("/settings/runtime")]);state.tasks=tasks.tasks||[];state.programs=programs.programs||[];state.accounts=accounts.accounts||[];state.runtime=runtime.settings||{};$("tasksTable").innerHTML=table(["任务","程序","账户范围","Task 状态","计划","操作"],state.tasks.map(taskRow),"尚无任务，请创建第一个任务");$("taskProgram").innerHTML=`<option value="">请选择</option>${state.programs.map(p=>`<option value="${esc(p.name)}">${esc(p.title||p.name)} (${esc(p.version||"-")})</option>`).join("")}`;$("taskAccounts").innerHTML=state.accounts.map(a=>`<label><input type="checkbox" name="taskAccount" value="${esc(ident(a))}"> ${esc(a.name||a.display_name||ident(a))} ${a.username?`(@${esc(String(a.username).replace(/^@/,""))})`:""}</label>`).join("")||"<span class='muted'>请先配置账户</span>"}

function selectedProgram(){return state.programs.find(p=>p.name===$("taskProgram").value)}
function schemaOf(program){return program?.params_schema||program?.schema||program?.json_schema||{}}
function parseJSONField(id,fallback){const raw=$(id).value.trim();if(!raw)return fallback;try{return JSON.parse(raw)}catch{throw new Error(`${$(id).previousSibling?.textContent||id} 不是合法 JSON`)}}
function renderParamFields(){const program=selectedProgram();const schema=schemaOf(program);$("programHelp").textContent=program?.description||"";let values={};try{values=parseJSONField("taskParams",{})}catch{}const properties=schema.properties||{};const required=new Set(schema.required||[]);if(!Object.keys(properties).length){$("schemaHelp").innerHTML="当前程序未提供参数 Schema，请直接填写 JSON。";return}$("schemaHelp").innerHTML=`<strong>Schema 参数</strong><div class="grid two compact">${Object.entries(properties).map(([name,prop])=>paramControl(name,prop,values[name],required.has(name))).join("")}</div>`;document.querySelectorAll("[data-param]").forEach(input=>input.addEventListener("change",syncParamJSON))}
function paramControl(name,prop,value,isRequired){const label=`${esc(prop.title||name)}${isRequired?" *":""}`;const description=prop.description?`<small>${esc(prop.description)}</small>`:"";if(prop.enum)return `<label>${label}<select data-param="${esc(name)}" data-type="string">${prop.enum.map(x=>`<option value="${esc(x)}" ${x===(value??prop.default)?"selected":""}>${esc(x)}</option>`).join("")}</select>${description}</label>`;if(prop.type==="boolean")return `<label>${label}<select data-param="${esc(name)}" data-type="boolean"><option value="true" ${(value??prop.default)===true?"selected":""}>是</option><option value="false" ${(value??prop.default)===false?"selected":""}>否</option></select>${description}</label>`;if(prop.type==="integer"||prop.type==="number")return `<label>${label}<input data-param="${esc(name)}" data-type="${prop.type}" type="number" value="${esc(value??prop.default??"")}" ${prop.minimum!==undefined?`min="${esc(prop.minimum)}"`:""}>${description}</label>`;const raw=prop.type==="array"||prop.type==="object"?json(value??prop.default??(prop.type==="array"?[]:{})):value??prop.default??"";return `<label>${label}<input data-param="${esc(name)}" data-type="${esc(prop.type||"string")}" value="${esc(raw)}">${description}</label>`}
function syncParamJSON(){let result={};try{result=parseJSONField("taskParams",{})}catch{}document.querySelectorAll("[data-param]").forEach(input=>{if(input.value===""){delete result[input.dataset.param];return}const type=input.dataset.type;let value=input.value;if(type==="boolean")value=value==="true";else if(type==="integer")value=parseInt(value,10);else if(type==="number")value=parseFloat(value);else if(type==="array"||type==="object"){try{value=JSON.parse(value)}catch{return}}result[input.dataset.param]=value});$("taskParams").value=json(result)}
function openTaskEditor(task=null){$("taskEditor").classList.add("open");$("taskFormTitle").textContent=task?"编辑任务":"创建任务";$("taskId").value=task?.id||"";$("taskName").value=task?.name||"";$("taskDescription").value=task?.description||"";$("taskProgram").value=task?.program_name||"";$("taskParams").value=json(task?.params||{});$("taskBrowserPolicy").value=task?.browser_end_policy||state.runtime.default_browser_end_policy||"keep_open";$("taskEnabled").value=String(task?.enabled??true);$("taskSchedule").value=task?.schedule?json(task.schedule):"";const selected=new Set(task?.account_ids||[task?.account_id].filter(Boolean));document.querySelectorAll('[name="taskAccount"]').forEach(x=>x.checked=selected.has(x.value));renderParamFields()}

async function loadRuns(){const filter=$("runStatusFilter").value;const data=await api(`/task-runs${filter?`?status=${encodeURIComponent(filter)}`:""}`);state.runs=data.runs||[];const rows=state.runs.map(run=>`<tr><td><button class="link-button" data-run-view="${esc(run.id)}">${esc(run.id)}</button><div class="muted">${esc(run.trigger||run.trigger_type||"manual")}</div></td><td>${esc(run.task_name||run.task_id||"-")}<div class="muted"><code>${esc(run.program_name)}</code></div></td><td>${esc(run.account_name||run.account_id)}</td><td>${statusBadge(run.status)}</td><td>${when(run.created_at)}<div class="muted">${run.started_at?`开始 ${when(run.started_at)}`:""}</div></td><td><div class="row-actions">${["queued","running"].includes(run.status)?`<button class="link-button" data-run-cancel="${esc(run.id)}">取消</button>`:`<button class="danger" data-run-delete="${esc(run.id)}">删除</button>`}<button class="link-button" data-run-rerun="${esc(run.id)}">重新运行</button></div></td></tr>`);$("runsTable").innerHTML=table(["Run ID / 触发","任务 / 程序","账户","TaskRun 状态","时间","操作"],rows,"暂无运行记录");if(state.selectedRun)await showRun(state.selectedRun)}
async function showRun(id){state.selectedRun=id;const [runData,logData]=await Promise.all([api(`/task-runs/${id}`),api(`/task-runs/${id}/logs`)]);const run=runData.run;const logs=logData.logs||[];const runAction=["queued","running"].includes(run.status)?`<button class="danger" data-run-cancel="${esc(run.id)}">请求取消</button>`:`<button class="danger" data-run-delete="${esc(run.id)}">删除记录</button>`;$("runDetail").innerHTML=`<div class="panel-head"><div><h2>运行详情</h2><code>${esc(run.id)}</code></div>${runAction}</div><div class="grid two compact"><div><small class="muted">TaskRun 状态</small><div>${statusBadge(run.status)}</div></div><div><small class="muted">账户</small><div>${esc(run.account_name||run.account_id)}</div></div><div><small class="muted">程序</small><div>${esc(run.program_name)} ${esc(run.program_version||"")}</div></div><div><small class="muted">浏览器结束策略</small><div>${esc(run.browser_end_policy||"keep_open")}</div></div><div><small class="muted">开始</small><div>${when(run.started_at)}</div></div><div><small class="muted">结束</small><div>${when(run.finished_at)}</div></div></div><h3>参数快照</h3><pre class="json">${esc(json(run.params||run.params_snapshot||{}))}</pre><h3>输出</h3><pre class="json">${esc(json(run.output||{}))}</pre>${run.error?`<h3>错误</h3><pre class="json">${esc(json(run.error))}</pre>`:""}${run.cleanup_warnings?.length?`<h3>清理告警</h3><pre class="json">${esc(json(run.cleanup_warnings))}</pre>`:""}<div class="panel-head"><h3>运行日志</h3><button class="secondary" data-run-view="${esc(run.id)}">刷新日志</button></div><div class="logs">${logs.length?logs.map(log=>`<div class="log ${esc(log.level||"")}"><span class="log-time">${when(log.created_at||log.timestamp)}</span><strong>${esc(log.level||"INFO")}</strong> ${esc(log.message)}${log.fields&&Object.keys(log.fields).length?`<pre>${esc(json(log.fields))}</pre>`:""}</div>`).join(""):`<div class="empty">暂无日志</div>`}</div>`}

async function loadAI(){const [settings,templates]=await Promise.all([api("/ai/settings"),api("/ai/templates")]);$("aiProvider").value=settings.provider||"openai";$("aiBaseUrl").value=settings.base_url||"";$("aiModel").value=settings.model||"";$("aiTimeout").value=settings.timeout_seconds||30;$("aiApiKey").value="";$("aiKeyState").textContent=settings.api_key_configured?"API Key 已配置，查询接口不会返回明文。":"尚未配置 API Key。";$("templatesList").innerHTML=(templates.templates||[]).map(t=>`<div class="template-item"><strong>${esc(t.name)} <code>${esc(t.id)}</code></strong><span class="muted">${t.enabled?"启用":"停用"} · 变量：${esc((t.variables||[]).join(", ")||"无")}</span></div>`).join("")||`<div class="empty">暂无模板</div>`}
async function loadSettings(){const data=await api("/settings/runtime");const s=data.settings||{};$("maxConcurrent").value=s.max_concurrent_browser_tasks;$("cancelPoll").value=s.cancellation_poll_interval_seconds;$("taskTimeout").value=s.default_task_timeout_seconds;$("browserAcquireTimeout").value=s.browser_acquire_timeout_seconds;$("defaultBrowserPolicy").value=s.default_browser_end_policy;$("logRetention").value=s.task_log_retention_days;$("queuePoll").value=s.queue_poll_interval_seconds;const st=data.status||{};$("serviceStatus").innerHTML=Object.entries(st).map(([key,value])=>`<div class="template-item"><strong>${esc(key)}</strong><span>${typeof value==="boolean"?statusBadge(value?"running":"error"):esc(value)}</span></div>`).join("")||`<div class="empty">暂无状态信息</div>`}

const loaders={dashboard:loadDashboard,accounts:loadAccounts,tasks:loadTasks,runs:loadRuns,programs:loadPrograms,ai:loadAI,settings:loadSettings};
document.addEventListener("click",async event=>{const target=event.target.closest("button");if(!target)return;try{if(target.dataset.page)return showPage(target.dataset.page);if(target.id==="refreshPage")return showPage(state.page);if(target.dataset.browser){await api(`/accounts/${target.dataset.account}/browser/${target.dataset.browser}`,{method:"POST"});flash("浏览器操作已完成");return loadAccounts()}if(target.dataset.batch){const ids=[...document.querySelectorAll(".account-select:checked")].map(x=>x.value);if(!ids.length)throw new Error("请至少选择一个账户");await api("/accounts/browser/batch",{method:"POST",body:json({action:target.dataset.batch,account_ids:ids})});flash("批量浏览器操作已提交");return loadAccounts()}if(target.id==="newTask")return openTaskEditor();if(target.id==="closeTaskEditor")return $("taskEditor").classList.remove("open");if(target.dataset.taskEdit)return openTaskEditor(state.tasks.find(t=>t.id===target.dataset.taskEdit));if(target.dataset.taskRun){const result=await api(`/tasks/${target.dataset.taskRun}/run`,{method:"POST"});flash(`已创建 ${(result.runs||result.run_ids||[]).length||1} 条 TaskRun`);return loadTasks()}if(target.dataset.taskClone){await api(`/tasks/${target.dataset.taskClone}/clone`,{method:"POST"});flash("任务已复制");return loadTasks()}if(target.dataset.taskToggle){await api(`/tasks/${target.dataset.taskToggle}/${target.dataset.enabled==="true"?"enable":"disable"}`,{method:"POST"});return loadTasks()}if(target.dataset.taskDelete){if(!confirm(`确定删除任务“${target.dataset.taskName||target.dataset.taskDelete}”吗？历史运行记录会保留。`))return;await api(`/tasks/${target.dataset.taskDelete}`,{method:"DELETE"});if($("taskId").value===target.dataset.taskDelete)$("taskEditor").classList.remove("open");flash("任务已删除，历史运行记录已保留");return loadTasks()}if(target.dataset.runView){await showPage("runs");return showRun(target.dataset.runView)}if(target.dataset.runCancel){await api(`/task-runs/${target.dataset.runCancel}/cancel`,{method:"POST"});flash("取消请求已提交；running 状态将在协作式检查点退出");return state.page==="dashboard"?loadDashboard():loadRuns()}if(target.dataset.runDelete){if(!confirm(`确定删除运行记录 ${target.dataset.runDelete} 吗？该记录的日志也会一并删除。`))return;await api(`/task-runs/${target.dataset.runDelete}`,{method:"DELETE"});if(state.selectedRun===target.dataset.runDelete){state.selectedRun=null;$("runDetail").replaceChildren()}flash("运行记录及其日志已删除");return loadRuns()}if(target.dataset.runRerun){await api(`/task-runs/${target.dataset.runRerun}/rerun`,{method:"POST"});flash("已用原参数快照创建新的 TaskRun");return loadRuns()}if(target.id==="validateParams"){syncParamJSON();JSON.parse($("taskParams").value);flash("参数 JSON 格式有效，服务端保存时还会按程序 Schema 校验")}if(target.id==="testAI"){const result=await api("/ai/test",{method:"POST",body:json({prompt:"请只回复：连接测试成功"})});flash(result.message||(result.ok?"连接成功":"连接失败"),!result.ok)}if(target.id==="newTemplate")$("templateForm").classList.toggle("hidden")}catch(error){flash(error.message,true)}});

$("taskProgram").addEventListener("change",renderParamFields);$("runStatusFilter").addEventListener("change",loadRuns);
$("taskForm").addEventListener("submit",async event=>{event.preventDefault();try{syncParamJSON();const id=$("taskId").value;const payload={name:$("taskName").value.trim(),description:$("taskDescription").value.trim(),program_name:$("taskProgram").value,account_ids:[...document.querySelectorAll('[name="taskAccount"]:checked')].map(x=>x.value),params:parseJSONField("taskParams",{}),enabled:$("taskEnabled").value==="true",browser_end_policy:$("taskBrowserPolicy").value,schedule:parseJSONField("taskSchedule",null)};if(!payload.account_ids.length)throw new Error("请至少选择一个账户");await api(id?`/tasks/${id}`:"/tasks",{method:id?"PUT":"POST",body:json(payload)});flash(id?"任务已更新":"任务已创建");$("taskEditor").classList.remove("open");await loadTasks()}catch(error){flash(error.message,true)}});
$("aiForm").addEventListener("submit",async event=>{event.preventDefault();try{await api("/ai/settings",{method:"PUT",body:json({provider:$("aiProvider").value,base_url:$("aiBaseUrl").value,api_key:$("aiApiKey").value||null,model:$("aiModel").value,timeout_seconds:Number($("aiTimeout").value)})});flash("AI 配置已保存");await loadAI()}catch(error){flash(error.message,true)}});
$("templateForm").addEventListener("submit",async event=>{event.preventDefault();try{await api("/ai/templates",{method:"POST",body:json({id:$("templateId").value,name:$("templateName").value,system_prompt:$("templateSystem").value,user_prompt:$("templateUser").value,variables:$("templateVariables").value.split(",").map(x=>x.trim()).filter(Boolean),model:null,enabled:true})});flash("模板已保存");$("templateForm").classList.add("hidden");await loadAI()}catch(error){flash(error.message,true)}});
$("runtimeForm").addEventListener("submit",async event=>{event.preventDefault();try{await api("/settings/runtime",{method:"PUT",body:json({max_concurrent_browser_tasks:Number($("maxConcurrent").value),cancellation_poll_interval_seconds:Number($("cancelPoll").value),default_task_timeout_seconds:Number($("taskTimeout").value),browser_acquire_timeout_seconds:Number($("browserAcquireTimeout").value),default_browser_end_policy:$("defaultBrowserPolicy").value,task_log_retention_days:Number($("logRetention").value),queue_poll_interval_seconds:Number($("queuePoll").value)})});flash("运行设置已保存并应用");await loadSettings()}catch(error){flash(error.message,true)}});
showPage("dashboard");
